//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace goodtooDraft.Customers {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class xmldata {
        
        private xmldataCustomers[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataCustomers[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataCustomers {
        
        private object customerIDField;
        
        private object accessKeyField;
        
        private object allow_Access_To_Private_SectionsField;
        
        private object billingAddress1Field;
        
        private object billingAddress2Field;
        
        private object catalogSubscriberField;
        
        private object checkbox_For_New_CustomersField;
        
        private object cityField;
        
        private object companyNameField;
        
        private object countryField;
        
        private object custom_Field_Custom1Field;
        
        private object custom_Field_Custom2Field;
        
        private object custom_Field_Custom3Field;
        
        private object custom_Field_Custom4Field;
        
        private object custom_Field_Custom5Field;
        
        private object customer_IsAnonymousField;
        
        private object customer_NotesField;
        
        private object customerTypeField;
        
        private object discountLevelField;
        
        private object emailAddressField;
        
        private object emailSubscriberField;
        
        private object faxNumberField;
        
        private object firstDateVisitedField;
        
        private object firstNameField;
        
        private object firstOrderDateField;
        
        private object iD_Customers_GroupsField;
        
        private object isSuperAdminField;
        
        private object lastLoginField;
        
        private object lastLoginAttemptField;
        
        private object lastModByField;
        
        private object lastModifiedField;
        
        private object lastNameField;
        
        private object loginAttemptsField;
        
        private object news1Field;
        
        private object news10Field;
        
        private object news11Field;
        
        private object news12Field;
        
        private object news13Field;
        
        private object news14Field;
        
        private object news15Field;
        
        private object news16Field;
        
        private object news17Field;
        
        private object news18Field;
        
        private object news19Field;
        
        private object news2Field;
        
        private object news20Field;
        
        private object news3Field;
        
        private object news4Field;
        
        private object news5Field;
        
        private object news6Field;
        
        private object news7Field;
        
        private object news8Field;
        
        private object news9Field;
        
        private object passwordField;
        
        private object paysStateTaxField;
        
        private object percentDiscountField;
        
        private object phoneNumberField;
        
        private object postalCodeField;
        
        private object salesRep_CustomerIDField;
        
        private object stateField;
        
        private object taxIDField;
        
        private object websiteAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AccessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Allow_Access_To_Private_Sections {
            get {
                return this.allow_Access_To_Private_SectionsField;
            }
            set {
                this.allow_Access_To_Private_SectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CatalogSubscriber {
            get {
                return this.catalogSubscriberField;
            }
            set {
                this.catalogSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Checkbox_For_New_Customers {
            get {
                return this.checkbox_For_New_CustomersField;
            }
            set {
                this.checkbox_For_New_CustomersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom1 {
            get {
                return this.custom_Field_Custom1Field;
            }
            set {
                this.custom_Field_Custom1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom2 {
            get {
                return this.custom_Field_Custom2Field;
            }
            set {
                this.custom_Field_Custom2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom3 {
            get {
                return this.custom_Field_Custom3Field;
            }
            set {
                this.custom_Field_Custom3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom4 {
            get {
                return this.custom_Field_Custom4Field;
            }
            set {
                this.custom_Field_Custom4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom5 {
            get {
                return this.custom_Field_Custom5Field;
            }
            set {
                this.custom_Field_Custom5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Customer_IsAnonymous {
            get {
                return this.customer_IsAnonymousField;
            }
            set {
                this.customer_IsAnonymousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Customer_Notes {
            get {
                return this.customer_NotesField;
            }
            set {
                this.customer_NotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountLevel {
            get {
                return this.discountLevelField;
            }
            set {
                this.discountLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EmailSubscriber {
            get {
                return this.emailSubscriberField;
            }
            set {
                this.emailSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FirstDateVisited {
            get {
                return this.firstDateVisitedField;
            }
            set {
                this.firstDateVisitedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FirstOrderDate {
            get {
                return this.firstOrderDateField;
            }
            set {
                this.firstOrderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ID_Customers_Groups {
            get {
                return this.iD_Customers_GroupsField;
            }
            set {
                this.iD_Customers_GroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsSuperAdmin {
            get {
                return this.isSuperAdminField;
            }
            set {
                this.isSuperAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                this.lastLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastLoginAttempt {
            get {
                return this.lastLoginAttemptField;
            }
            set {
                this.lastLoginAttemptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModBy {
            get {
                return this.lastModByField;
            }
            set {
                this.lastModByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LoginAttempts {
            get {
                return this.loginAttemptsField;
            }
            set {
                this.loginAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news1 {
            get {
                return this.news1Field;
            }
            set {
                this.news1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news10 {
            get {
                return this.news10Field;
            }
            set {
                this.news10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news11 {
            get {
                return this.news11Field;
            }
            set {
                this.news11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news12 {
            get {
                return this.news12Field;
            }
            set {
                this.news12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news13 {
            get {
                return this.news13Field;
            }
            set {
                this.news13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news14 {
            get {
                return this.news14Field;
            }
            set {
                this.news14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news15 {
            get {
                return this.news15Field;
            }
            set {
                this.news15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news16 {
            get {
                return this.news16Field;
            }
            set {
                this.news16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news17 {
            get {
                return this.news17Field;
            }
            set {
                this.news17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news18 {
            get {
                return this.news18Field;
            }
            set {
                this.news18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news19 {
            get {
                return this.news19Field;
            }
            set {
                this.news19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news2 {
            get {
                return this.news2Field;
            }
            set {
                this.news2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news20 {
            get {
                return this.news20Field;
            }
            set {
                this.news20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news3 {
            get {
                return this.news3Field;
            }
            set {
                this.news3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news4 {
            get {
                return this.news4Field;
            }
            set {
                this.news4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news5 {
            get {
                return this.news5Field;
            }
            set {
                this.news5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news6 {
            get {
                return this.news6Field;
            }
            set {
                this.news6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news7 {
            get {
                return this.news7Field;
            }
            set {
                this.news7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news8 {
            get {
                return this.news8Field;
            }
            set {
                this.news8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object news9 {
            get {
                return this.news9Field;
            }
            set {
                this.news9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PaysStateTax {
            get {
                return this.paysStateTaxField;
            }
            set {
                this.paysStateTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PercentDiscount {
            get {
                return this.percentDiscountField;
            }
            set {
                this.percentDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesRep_CustomerID {
            get {
                return this.salesRep_CustomerIDField;
            }
            set {
                this.salesRep_CustomerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TaxID {
            get {
                return this.taxIDField;
            }
            set {
                this.taxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object WebsiteAddress {
            get {
                return this.websiteAddressField;
            }
            set {
                this.websiteAddressField = value;
            }
        }
    }
}
