//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace goodtooDraft.Orders {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class xmldata {
        
        private xmldataOrders[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Orders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataOrders[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataOrders {
        
        private object orderIDField;
        
        private object accountNumberField;
        
        private object accountTypeField;
        
        private object addressValidatedField;
        
        private object affiliate_Commissionable_ValueField;
        
        private object aVSField;
        
        private object bankNameField;
        
        private object batchNumberField;
        
        private object billingAddress1Field;
        
        private object billingAddress2Field;
        
        private object billingCityField;
        
        private object billingCompanyNameField;
        
        private object billingCountryField;
        
        private object billingFaxNumberField;
        
        private object billingFirstNameField;
        
        private object billingLastNameField;
        
        private object billingPhoneNumberField;
        
        private object billingPostalCodeField;
        
        private object billingStateField;
        
        private object cardHoldersNameField;
        
        private object cashTenderField;
        
        private object cC_Last4Field;
        
        private object checkNumberField;
        
        private object creditCardAuthorizationDateField;
        
        private object creditCardAuthorizationNumberField;
        
        private object creditCardExpDateField;
        
        private object creditCardIssueDateField;
        
        private object creditCardIssueNumberField;
        
        private object creditCardTransactionIDField;
        
        private object custom_Field_Custom1Field;
        
        private object custom_Field_Custom2Field;
        
        private object custom_Field_Custom3Field;
        
        private object custom_Field_Custom4Field;
        
        private object custom_Field_Custom5Field;
        
        private object customer_IPAddressField;
        
        private object customerIDField;
        
        private object cVV2_ResponseField;
        
        private object dV_CreditCardNumberField;
        
        private object giftCardIDUsedField;
        
        private object isAGiftField;
        
        private object lastModByField;
        
        private object lastModifiedField;
        
        private object lockedField;
        
        private object mICRField;
        
        private object order_CommentsField;
        
        private object order_Entry_SystemField;
        
        private object orderDateField;
        
        private object orderID_EDIField;
        
        private object orderID_Third_PartyField;
        
        private object orderNotesField;
        
        private object orderStatusField;
        
        private object paymentAmountField;
        
        private object paymentDeclinedField;
        
        private object paymentMethodIDField;
        
        private object pONumField;
        
        private object printedField;
        
        private object processed_AutoEventsField;
        
        private object routingNumberField;
        
        private object salesRep_CustomerIDField;
        
        private object salesTax1Field;
        
        private object salesTax2Field;
        
        private object salesTax3Field;
        
        private object salesTaxRateField;
        
        private object salesTaxRate1Field;
        
        private object salesTaxRate2Field;
        
        private object salesTaxRate3Field;
        
        private object shipAddress1Field;
        
        private object shipAddress2Field;
        
        private object shipCityField;
        
        private object shipCompanyNameField;
        
        private object shipCountryField;
        
        private object shipDateField;
        
        private object shipFaxNumberField;
        
        private object shipFirstNameField;
        
        private object shipLastNameField;
        
        private object shippedField;
        
        private object shipPhoneNumberField;
        
        private object shipping_LockedField;
        
        private object shippingMethodIDField;
        
        private object shipPostalCodeField;
        
        private object shipResidentialField;
        
        private object shipStateField;
        
        private object stock_PriorityField;
        
        private object tax1_TitleField;
        
        private object tax2_TitleField;
        
        private object tax3_TitleField;
        
        private object total_Payment_AuthorizedField;
        
        private object total_Payment_ReceivedField;
        
        private object totalShippingCostField;
        
        private object vendorIDField;
        
        private xmldataOrdersOrderDetails[] orderDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AddressValidated {
            get {
                return this.addressValidatedField;
            }
            set {
                this.addressValidatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Affiliate_Commissionable_Value {
            get {
                return this.affiliate_Commissionable_ValueField;
            }
            set {
                this.affiliate_Commissionable_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AVS {
            get {
                return this.aVSField;
            }
            set {
                this.aVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingCompanyName {
            get {
                return this.billingCompanyNameField;
            }
            set {
                this.billingCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingCountry {
            get {
                return this.billingCountryField;
            }
            set {
                this.billingCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingFaxNumber {
            get {
                return this.billingFaxNumberField;
            }
            set {
                this.billingFaxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingFirstName {
            get {
                return this.billingFirstNameField;
            }
            set {
                this.billingFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingLastName {
            get {
                return this.billingLastNameField;
            }
            set {
                this.billingLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingPhoneNumber {
            get {
                return this.billingPhoneNumberField;
            }
            set {
                this.billingPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingPostalCode {
            get {
                return this.billingPostalCodeField;
            }
            set {
                this.billingPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object BillingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CardHoldersName {
            get {
                return this.cardHoldersNameField;
            }
            set {
                this.cardHoldersNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CashTender {
            get {
                return this.cashTenderField;
            }
            set {
                this.cashTenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CC_Last4 {
            get {
                return this.cC_Last4Field;
            }
            set {
                this.cC_Last4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardAuthorizationDate {
            get {
                return this.creditCardAuthorizationDateField;
            }
            set {
                this.creditCardAuthorizationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardAuthorizationNumber {
            get {
                return this.creditCardAuthorizationNumberField;
            }
            set {
                this.creditCardAuthorizationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardExpDate {
            get {
                return this.creditCardExpDateField;
            }
            set {
                this.creditCardExpDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardIssueDate {
            get {
                return this.creditCardIssueDateField;
            }
            set {
                this.creditCardIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardIssueNumber {
            get {
                return this.creditCardIssueNumberField;
            }
            set {
                this.creditCardIssueNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CreditCardTransactionID {
            get {
                return this.creditCardTransactionIDField;
            }
            set {
                this.creditCardTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom1 {
            get {
                return this.custom_Field_Custom1Field;
            }
            set {
                this.custom_Field_Custom1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom2 {
            get {
                return this.custom_Field_Custom2Field;
            }
            set {
                this.custom_Field_Custom2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom3 {
            get {
                return this.custom_Field_Custom3Field;
            }
            set {
                this.custom_Field_Custom3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom4 {
            get {
                return this.custom_Field_Custom4Field;
            }
            set {
                this.custom_Field_Custom4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Custom_Field_Custom5 {
            get {
                return this.custom_Field_Custom5Field;
            }
            set {
                this.custom_Field_Custom5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Customer_IPAddress {
            get {
                return this.customer_IPAddressField;
            }
            set {
                this.customer_IPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CVV2_Response {
            get {
                return this.cVV2_ResponseField;
            }
            set {
                this.cVV2_ResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DV_CreditCardNumber {
            get {
                return this.dV_CreditCardNumberField;
            }
            set {
                this.dV_CreditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftCardIDUsed {
            get {
                return this.giftCardIDUsedField;
            }
            set {
                this.giftCardIDUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsAGift {
            get {
                return this.isAGiftField;
            }
            set {
                this.isAGiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModBy {
            get {
                return this.lastModByField;
            }
            set {
                this.lastModByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object MICR {
            get {
                return this.mICRField;
            }
            set {
                this.mICRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Order_Comments {
            get {
                return this.order_CommentsField;
            }
            set {
                this.order_CommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Order_Entry_System {
            get {
                return this.order_Entry_SystemField;
            }
            set {
                this.order_Entry_SystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderID_EDI {
            get {
                return this.orderID_EDIField;
            }
            set {
                this.orderID_EDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderID_Third_Party {
            get {
                return this.orderID_Third_PartyField;
            }
            set {
                this.orderID_Third_PartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderNotes {
            get {
                return this.orderNotesField;
            }
            set {
                this.orderNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PaymentDeclined {
            get {
                return this.paymentDeclinedField;
            }
            set {
                this.paymentDeclinedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PaymentMethodID {
            get {
                return this.paymentMethodIDField;
            }
            set {
                this.paymentMethodIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PONum {
            get {
                return this.pONumField;
            }
            set {
                this.pONumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Printed {
            get {
                return this.printedField;
            }
            set {
                this.printedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Processed_AutoEvents {
            get {
                return this.processed_AutoEventsField;
            }
            set {
                this.processed_AutoEventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RoutingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesRep_CustomerID {
            get {
                return this.salesRep_CustomerIDField;
            }
            set {
                this.salesRep_CustomerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTax1 {
            get {
                return this.salesTax1Field;
            }
            set {
                this.salesTax1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTax2 {
            get {
                return this.salesTax2Field;
            }
            set {
                this.salesTax2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTax3 {
            get {
                return this.salesTax3Field;
            }
            set {
                this.salesTax3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTaxRate {
            get {
                return this.salesTaxRateField;
            }
            set {
                this.salesTaxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTaxRate1 {
            get {
                return this.salesTaxRate1Field;
            }
            set {
                this.salesTaxRate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTaxRate2 {
            get {
                return this.salesTaxRate2Field;
            }
            set {
                this.salesTaxRate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalesTaxRate3 {
            get {
                return this.salesTaxRate3Field;
            }
            set {
                this.salesTaxRate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipAddress1 {
            get {
                return this.shipAddress1Field;
            }
            set {
                this.shipAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipAddress2 {
            get {
                return this.shipAddress2Field;
            }
            set {
                this.shipAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipCity {
            get {
                return this.shipCityField;
            }
            set {
                this.shipCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipCompanyName {
            get {
                return this.shipCompanyNameField;
            }
            set {
                this.shipCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipCountry {
            get {
                return this.shipCountryField;
            }
            set {
                this.shipCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipFaxNumber {
            get {
                return this.shipFaxNumberField;
            }
            set {
                this.shipFaxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipFirstName {
            get {
                return this.shipFirstNameField;
            }
            set {
                this.shipFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipLastName {
            get {
                return this.shipLastNameField;
            }
            set {
                this.shipLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Shipped {
            get {
                return this.shippedField;
            }
            set {
                this.shippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipPhoneNumber {
            get {
                return this.shipPhoneNumberField;
            }
            set {
                this.shipPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Shipping_Locked {
            get {
                return this.shipping_LockedField;
            }
            set {
                this.shipping_LockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShippingMethodID {
            get {
                return this.shippingMethodIDField;
            }
            set {
                this.shippingMethodIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipPostalCode {
            get {
                return this.shipPostalCodeField;
            }
            set {
                this.shipPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipResidential {
            get {
                return this.shipResidentialField;
            }
            set {
                this.shipResidentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipState {
            get {
                return this.shipStateField;
            }
            set {
                this.shipStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Stock_Priority {
            get {
                return this.stock_PriorityField;
            }
            set {
                this.stock_PriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Tax1_Title {
            get {
                return this.tax1_TitleField;
            }
            set {
                this.tax1_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Tax2_Title {
            get {
                return this.tax2_TitleField;
            }
            set {
                this.tax2_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Tax3_Title {
            get {
                return this.tax3_TitleField;
            }
            set {
                this.tax3_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Total_Payment_Authorized {
            get {
                return this.total_Payment_AuthorizedField;
            }
            set {
                this.total_Payment_AuthorizedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Total_Payment_Received {
            get {
                return this.total_Payment_ReceivedField;
            }
            set {
                this.total_Payment_ReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TotalShippingCost {
            get {
                return this.totalShippingCostField;
            }
            set {
                this.totalShippingCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object VendorID {
            get {
                return this.vendorIDField;
            }
            set {
                this.vendorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataOrdersOrderDetails[] OrderDetails {
            get {
                return this.orderDetailsField;
            }
            set {
                this.orderDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataOrdersOrderDetails {
        
        private object orderDetailIDField;
        
        private object affiliate_Commissionable_ValueField;
        
        private object autoDropShipField;
        
        private object categoryIDField;
        
        private object couponCodeField;
        
        private object customLineItemField;
        
        private object discountAutoIDField;
        
        private object downloadFileField;
        
        private object fixed_ShippingCostField;
        
        private object fixed_ShippingCost_Outside_LocalRegionField;
        
        private object freeShippingItemField;
        
        private object giftTrakNumberField;
        
        private object giftWrapField;
        
        private object giftWrapCostField;
        
        private object giftWrapNoteField;
        
        private object isKitIDField;
        
        private object kitIDField;
        
        private object lastModByField;
        
        private object lastModifiedField;
        
        private object lockedField;
        
        private object onOrder_QtyField;
        
        private object optionIDField;
        
        private object optionIDsField;
        
        private object optionsField;
        
        private object orderDetailID_EDIField;
        
        private object orderIDField;
        
        private object product_Keys_ShippedField;
        
        private object productCodeField;
        
        private object productIDField;
        
        private object productNameField;
        
        private object productNoteField;
        
        private object productPriceField;
        
        private object productWeightField;
        
        private object qtyOnBackOrderField;
        
        private object qtyOnHoldField;
        
        private object qtyOnPackingSlipField;
        
        private object qtyShippedField;
        
        private object quantityField;
        
        private object returnedField;
        
        private object returned_DateField;
        
        private object rMA_NumberField;
        
        private object rMAI_IDField;
        
        private object shipDateField;
        
        private object shippedField;
        
        private object taxableProductField;
        
        private object totalPriceField;
        
        private object vendor_PriceField;
        
        private object warehousesField;
        
        private xmldataOrdersOrderDetailsOrderDetails_Options[] orderDetails_OptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDetailID {
            get {
                return this.orderDetailIDField;
            }
            set {
                this.orderDetailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Affiliate_Commissionable_Value {
            get {
                return this.affiliate_Commissionable_ValueField;
            }
            set {
                this.affiliate_Commissionable_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AutoDropShip {
            get {
                return this.autoDropShipField;
            }
            set {
                this.autoDropShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CouponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomLineItem {
            get {
                return this.customLineItemField;
            }
            set {
                this.customLineItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountAutoID {
            get {
                return this.discountAutoIDField;
            }
            set {
                this.discountAutoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DownloadFile {
            get {
                return this.downloadFileField;
            }
            set {
                this.downloadFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost {
            get {
                return this.fixed_ShippingCostField;
            }
            set {
                this.fixed_ShippingCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost_Outside_LocalRegion {
            get {
                return this.fixed_ShippingCost_Outside_LocalRegionField;
            }
            set {
                this.fixed_ShippingCost_Outside_LocalRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FreeShippingItem {
            get {
                return this.freeShippingItemField;
            }
            set {
                this.freeShippingItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftTrakNumber {
            get {
                return this.giftTrakNumberField;
            }
            set {
                this.giftTrakNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrap {
            get {
                return this.giftWrapField;
            }
            set {
                this.giftWrapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrapCost {
            get {
                return this.giftWrapCostField;
            }
            set {
                this.giftWrapCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrapNote {
            get {
                return this.giftWrapNoteField;
            }
            set {
                this.giftWrapNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsKitID {
            get {
                return this.isKitIDField;
            }
            set {
                this.isKitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object KitID {
            get {
                return this.kitIDField;
            }
            set {
                this.kitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModBy {
            get {
                return this.lastModByField;
            }
            set {
                this.lastModByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OnOrder_Qty {
            get {
                return this.onOrder_QtyField;
            }
            set {
                this.onOrder_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OptionIDs {
            get {
                return this.optionIDsField;
            }
            set {
                this.optionIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDetailID_EDI {
            get {
                return this.orderDetailID_EDIField;
            }
            set {
                this.orderDetailID_EDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Product_Keys_Shipped {
            get {
                return this.product_Keys_ShippedField;
            }
            set {
                this.product_Keys_ShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductNote {
            get {
                return this.productNoteField;
            }
            set {
                this.productNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductPrice {
            get {
                return this.productPriceField;
            }
            set {
                this.productPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductWeight {
            get {
                return this.productWeightField;
            }
            set {
                this.productWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnBackOrder {
            get {
                return this.qtyOnBackOrderField;
            }
            set {
                this.qtyOnBackOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnHold {
            get {
                return this.qtyOnHoldField;
            }
            set {
                this.qtyOnHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnPackingSlip {
            get {
                return this.qtyOnPackingSlipField;
            }
            set {
                this.qtyOnPackingSlipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyShipped {
            get {
                return this.qtyShippedField;
            }
            set {
                this.qtyShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Returned {
            get {
                return this.returnedField;
            }
            set {
                this.returnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Returned_Date {
            get {
                return this.returned_DateField;
            }
            set {
                this.returned_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RMA_Number {
            get {
                return this.rMA_NumberField;
            }
            set {
                this.rMA_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RMAI_ID {
            get {
                return this.rMAI_IDField;
            }
            set {
                this.rMAI_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Shipped {
            get {
                return this.shippedField;
            }
            set {
                this.shippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TaxableProduct {
            get {
                return this.taxableProductField;
            }
            set {
                this.taxableProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TotalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Vendor_Price {
            get {
                return this.vendor_PriceField;
            }
            set {
                this.vendor_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Warehouses {
            get {
                return this.warehousesField;
            }
            set {
                this.warehousesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails_Options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataOrdersOrderDetailsOrderDetails_Options[] OrderDetails_Options {
            get {
                return this.orderDetails_OptionsField;
            }
            set {
                this.orderDetails_OptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataOrdersOrderDetailsOrderDetails_Options {
        
        private object optionIDField;
        
        private object orderDetailIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDetailID {
            get {
                return this.orderDetailIDField;
            }
            set {
                this.orderDetailIDField = value;
            }
        }
    }
}
