//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace goodtooDraft.OrderDetails {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class xmldata {
        
        private xmldataOrderDetails[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataOrderDetails[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataOrderDetails {
        
        private object orderDetailIDField;
        
        private object affiliate_Commissionable_ValueField;
        
        private object autoDropShipField;
        
        private object categoryIDField;
        
        private object couponCodeField;
        
        private object customLineItemField;
        
        private object discountAutoIDField;
        
        private object downloadFileField;
        
        private object fixed_ShippingCostField;
        
        private object fixed_ShippingCost_Outside_LocalRegionField;
        
        private object freeShippingItemField;
        
        private object giftTrakNumberField;
        
        private object giftWrapField;
        
        private object giftWrapCostField;
        
        private object giftWrapNoteField;
        
        private object isKitIDField;
        
        private object kitIDField;
        
        private object lastModByField;
        
        private object lastModifiedField;
        
        private object lockedField;
        
        private object onOrder_QtyField;
        
        private object optionIDField;
        
        private object optionIDsField;
        
        private object optionsField;
        
        private object orderDetailID_EDIField;
        
        private object orderIDField;
        
        private object product_Keys_ShippedField;
        
        private object productCodeField;
        
        private object productIDField;
        
        private object productNameField;
        
        private object productNoteField;
        
        private object productPriceField;
        
        private object productWeightField;
        
        private object qtyOnBackOrderField;
        
        private object qtyOnHoldField;
        
        private object qtyOnPackingSlipField;
        
        private object qtyShippedField;
        
        private object quantityField;
        
        private object returnedField;
        
        private object returned_DateField;
        
        private object rMA_NumberField;
        
        private object rMAI_IDField;
        
        private object shipDateField;
        
        private object shippedField;
        
        private object taxableProductField;
        
        private object totalPriceField;
        
        private object vendor_PriceField;
        
        private object warehousesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDetailID {
            get {
                return this.orderDetailIDField;
            }
            set {
                this.orderDetailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Affiliate_Commissionable_Value {
            get {
                return this.affiliate_Commissionable_ValueField;
            }
            set {
                this.affiliate_Commissionable_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AutoDropShip {
            get {
                return this.autoDropShipField;
            }
            set {
                this.autoDropShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CouponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomLineItem {
            get {
                return this.customLineItemField;
            }
            set {
                this.customLineItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountAutoID {
            get {
                return this.discountAutoIDField;
            }
            set {
                this.discountAutoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DownloadFile {
            get {
                return this.downloadFileField;
            }
            set {
                this.downloadFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost {
            get {
                return this.fixed_ShippingCostField;
            }
            set {
                this.fixed_ShippingCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost_Outside_LocalRegion {
            get {
                return this.fixed_ShippingCost_Outside_LocalRegionField;
            }
            set {
                this.fixed_ShippingCost_Outside_LocalRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FreeShippingItem {
            get {
                return this.freeShippingItemField;
            }
            set {
                this.freeShippingItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftTrakNumber {
            get {
                return this.giftTrakNumberField;
            }
            set {
                this.giftTrakNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrap {
            get {
                return this.giftWrapField;
            }
            set {
                this.giftWrapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrapCost {
            get {
                return this.giftWrapCostField;
            }
            set {
                this.giftWrapCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrapNote {
            get {
                return this.giftWrapNoteField;
            }
            set {
                this.giftWrapNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsKitID {
            get {
                return this.isKitIDField;
            }
            set {
                this.isKitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object KitID {
            get {
                return this.kitIDField;
            }
            set {
                this.kitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModBy {
            get {
                return this.lastModByField;
            }
            set {
                this.lastModByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OnOrder_Qty {
            get {
                return this.onOrder_QtyField;
            }
            set {
                this.onOrder_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OptionIDs {
            get {
                return this.optionIDsField;
            }
            set {
                this.optionIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderDetailID_EDI {
            get {
                return this.orderDetailID_EDIField;
            }
            set {
                this.orderDetailID_EDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Product_Keys_Shipped {
            get {
                return this.product_Keys_ShippedField;
            }
            set {
                this.product_Keys_ShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductNote {
            get {
                return this.productNoteField;
            }
            set {
                this.productNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductPrice {
            get {
                return this.productPriceField;
            }
            set {
                this.productPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductWeight {
            get {
                return this.productWeightField;
            }
            set {
                this.productWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnBackOrder {
            get {
                return this.qtyOnBackOrderField;
            }
            set {
                this.qtyOnBackOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnHold {
            get {
                return this.qtyOnHoldField;
            }
            set {
                this.qtyOnHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyOnPackingSlip {
            get {
                return this.qtyOnPackingSlipField;
            }
            set {
                this.qtyOnPackingSlipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object QtyShipped {
            get {
                return this.qtyShippedField;
            }
            set {
                this.qtyShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Returned {
            get {
                return this.returnedField;
            }
            set {
                this.returnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Returned_Date {
            get {
                return this.returned_DateField;
            }
            set {
                this.returned_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RMA_Number {
            get {
                return this.rMA_NumberField;
            }
            set {
                this.rMA_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RMAI_ID {
            get {
                return this.rMAI_IDField;
            }
            set {
                this.rMAI_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Shipped {
            get {
                return this.shippedField;
            }
            set {
                this.shippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TaxableProduct {
            get {
                return this.taxableProductField;
            }
            set {
                this.taxableProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TotalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Vendor_Price {
            get {
                return this.vendor_PriceField;
            }
            set {
                this.vendor_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Warehouses {
            get {
                return this.warehousesField;
            }
            set {
                this.warehousesField = value;
            }
        }
    }
}
