//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace goodtooDraft.Products {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class xmldata {
        
        private xmldataProducts[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Products", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xmldataProducts[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class xmldataProducts {
        
        private object autoDropShipField;
        
        private object displayBeginDateField;
        
        private object displayEndDateField;
        
        private object doNotAllowBackOrdersField;
        
        private object hideProductField;
        
        private object homePage_SectionField;
        
        private object isChildOfProductCodeField;
        
        private object isChildOfProductCode_ProductIDField;
        
        private object lastModByField;
        
        private object lastModifiedField;
        
        private object options_Cloned_FromField;
        
        private object options_Cloned_From_ProductIDField;
        
        private object photos_Cloned_FromField;
        
        private object photos_Cloned_From_ProductIDField;
        
        private object productCodeField;
        
        private object productIDField;
        
        private object productNameField;
        
        private object productPopularityField;
        
        private object share_StockStatus_WithField;
        
        private object share_StockStatus_With_ProductIDField;
        
        private object stockStatusField;
        
        private object vendor_PartNoField;
        
        private object productDescriptionField;
        
        private object productDescriptionShortField;
        
        private object accessoriesField;
        
        private object additional_Handling_IndicatorField;
        
        private object addtoCartBtn_Replacement_TextField;
        
        private object addToPO_NowField;
        
        private object affiliate_Commissionable_ValueField;
        
        private object allowPriceEditField;
        
        private object availabilityField;
        
        private object book_ISBNField;
        
        private object customField1Field;
        
        private object customField2Field;
        
        private object customField3Field;
        
        private object customField4Field;
        
        private object customField5Field;
        
        private object discountedPrice_Level1Field;
        
        private object discountedPrice_Level2Field;
        
        private object discountedPrice_Level3Field;
        
        private object discountedPrice_Level4Field;
        
        private object discountedPrice_Level5Field;
        
        private object discountedRecurringPrice_Level1Field;
        
        private object discountedRecurringPrice_Level2Field;
        
        private object discountedRecurringPrice_Level3Field;
        
        private object discountedRecurringPrice_Level4Field;
        
        private object discountedRecurringPrice_Level5Field;
        
        private object discountedSetupCost_Level1Field;
        
        private object discountedSetupCost_Level2Field;
        
        private object discountedSetupCost_Level3Field;
        
        private object discountedSetupCost_Level4Field;
        
        private object discountedSetupCost_Level5Field;
        
        private object downloadFileField;
        
        private object enableMultiChildAddToCartField;
        
        private object enableOptions_InventoryControlField;
        
        private object estShip_2ndDayField;
        
        private object estShip_GroundField;
        
        private object estShip_OvernightField;
        
        private object fixed_ShippingCostField;
        
        private object fixed_ShippingCost_Outside_LocalRegionField;
        
        private object freeShippingItemField;
        
        private object giftWrapCostField;
        
        private object heightField;
        
        private object hide_FreeAccessoriesField;
        
        private object hide_When_OutOfStockField;
        
        private object hide_YouSaveField;
        
        private object howToGetSalePriceField;
        
        private object inv_LastVerifiedField;
        
        private object inv_Verify_QtyOnHandField;
        
        private object lastPO_DateField;
        
        private object lastPO_QtyField;
        
        private object lengthField;
        
        private object listPriceField;
        
        private object listPrice_NameField;
        
        private object maxQtyField;
        
        private object mETATAG_DescriptionField;
        
        private object mETATAG_TitleField;
        
        private object minQtyField;
        
        private object oversizedField;
        
        private object package_TypeField;
        
        private object photo_AltTextField;
        
        private object photo_SubTextField;
        
        private object photoURL_LargeField;
        
        private object photoURL_SmallField;
        
        private object price_SubTextField;
        
        private object price_SubText_ShortField;
        
        private object private_Section_Customers_OnlyField;
        
        private object productCategoryField;
        
        private object productConditionField;
        
        private object productKeywordsField;
        
        private object productManufacturerField;
        
        private object productNameShortField;
        
        private object productPriceField;
        
        private object productPrice_NameField;
        
        private object productWeightField;
        
        private object quickbooks_Item_AccntField;
        
        private object quickbooks_Item_AssetAccntField;
        
        private object quickbooks_Item_CogsAccntField;
        
        private object recurring_Pricing_TextField;
        
        private object recurringDurationField;
        
        private object recurringHowOftenField;
        
        private object recurringPriceField;
        
        private object recurringStartDurationField;
        
        private object recurringStartPriceField;
        
        private object salePriceField;
        
        private object salePrice_NameField;
        
        private object selectedOptionIDsField;
        
        private object setupCostField;
        
        private object setupCost_NameField;
        
        private object setupCost_TitleField;
        
        private object ships_By_ItselfField;
        
        private object shoppingDotCom_CategoryField;
        
        private object stockLowQtyAlarmField;
        
        private object stockReOrderQtyField;
        
        private object taxableProductField;
        
        private object uPC_codeField;
        
        private object uses_Product_KeyTypesField;
        
        private object vAT_PercentageField;
        
        private object vendor_PriceField;
        
        private object warehousesField;
        
        private object widthField;
        
        private object yahoo_CategoryField;
        
        private object yahoo_MediumField;
        
        private object cUSTOM_METATAGS_OVERRIDEField;
        
        private object extInfoField;
        
        private object mETATAG_KeywordsField;
        
        private object orderFinished_NoteField;
        
        private object productDescription_AbovePricingField;
        
        private object productFeaturesField;
        
        private object techSpecsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AutoDropShip {
            get {
                return this.autoDropShipField;
            }
            set {
                this.autoDropShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DisplayBeginDate {
            get {
                return this.displayBeginDateField;
            }
            set {
                this.displayBeginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DisplayEndDate {
            get {
                return this.displayEndDateField;
            }
            set {
                this.displayEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DoNotAllowBackOrders {
            get {
                return this.doNotAllowBackOrdersField;
            }
            set {
                this.doNotAllowBackOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object HideProduct {
            get {
                return this.hideProductField;
            }
            set {
                this.hideProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object HomePage_Section {
            get {
                return this.homePage_SectionField;
            }
            set {
                this.homePage_SectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsChildOfProductCode {
            get {
                return this.isChildOfProductCodeField;
            }
            set {
                this.isChildOfProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object IsChildOfProductCode_ProductID {
            get {
                return this.isChildOfProductCode_ProductIDField;
            }
            set {
                this.isChildOfProductCode_ProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModBy {
            get {
                return this.lastModByField;
            }
            set {
                this.lastModByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Options_Cloned_From {
            get {
                return this.options_Cloned_FromField;
            }
            set {
                this.options_Cloned_FromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Options_Cloned_From_ProductID {
            get {
                return this.options_Cloned_From_ProductIDField;
            }
            set {
                this.options_Cloned_From_ProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Photos_Cloned_From {
            get {
                return this.photos_Cloned_FromField;
            }
            set {
                this.photos_Cloned_FromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Photos_Cloned_From_ProductID {
            get {
                return this.photos_Cloned_From_ProductIDField;
            }
            set {
                this.photos_Cloned_From_ProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductPopularity {
            get {
                return this.productPopularityField;
            }
            set {
                this.productPopularityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Share_StockStatus_With {
            get {
                return this.share_StockStatus_WithField;
            }
            set {
                this.share_StockStatus_WithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Share_StockStatus_With_ProductID {
            get {
                return this.share_StockStatus_With_ProductIDField;
            }
            set {
                this.share_StockStatus_With_ProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object StockStatus {
            get {
                return this.stockStatusField;
            }
            set {
                this.stockStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Vendor_PartNo {
            get {
                return this.vendor_PartNoField;
            }
            set {
                this.vendor_PartNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductDescriptionShort {
            get {
                return this.productDescriptionShortField;
            }
            set {
                this.productDescriptionShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Accessories {
            get {
                return this.accessoriesField;
            }
            set {
                this.accessoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Additional_Handling_Indicator {
            get {
                return this.additional_Handling_IndicatorField;
            }
            set {
                this.additional_Handling_IndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AddtoCartBtn_Replacement_Text {
            get {
                return this.addtoCartBtn_Replacement_TextField;
            }
            set {
                this.addtoCartBtn_Replacement_TextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AddToPO_Now {
            get {
                return this.addToPO_NowField;
            }
            set {
                this.addToPO_NowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Affiliate_Commissionable_Value {
            get {
                return this.affiliate_Commissionable_ValueField;
            }
            set {
                this.affiliate_Commissionable_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AllowPriceEdit {
            get {
                return this.allowPriceEditField;
            }
            set {
                this.allowPriceEditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Book_ISBN {
            get {
                return this.book_ISBNField;
            }
            set {
                this.book_ISBNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomField1 {
            get {
                return this.customField1Field;
            }
            set {
                this.customField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomField2 {
            get {
                return this.customField2Field;
            }
            set {
                this.customField2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomField3 {
            get {
                return this.customField3Field;
            }
            set {
                this.customField3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomField4 {
            get {
                return this.customField4Field;
            }
            set {
                this.customField4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CustomField5 {
            get {
                return this.customField5Field;
            }
            set {
                this.customField5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedPrice_Level1 {
            get {
                return this.discountedPrice_Level1Field;
            }
            set {
                this.discountedPrice_Level1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedPrice_Level2 {
            get {
                return this.discountedPrice_Level2Field;
            }
            set {
                this.discountedPrice_Level2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedPrice_Level3 {
            get {
                return this.discountedPrice_Level3Field;
            }
            set {
                this.discountedPrice_Level3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedPrice_Level4 {
            get {
                return this.discountedPrice_Level4Field;
            }
            set {
                this.discountedPrice_Level4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedPrice_Level5 {
            get {
                return this.discountedPrice_Level5Field;
            }
            set {
                this.discountedPrice_Level5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedRecurringPrice_Level1 {
            get {
                return this.discountedRecurringPrice_Level1Field;
            }
            set {
                this.discountedRecurringPrice_Level1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedRecurringPrice_Level2 {
            get {
                return this.discountedRecurringPrice_Level2Field;
            }
            set {
                this.discountedRecurringPrice_Level2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedRecurringPrice_Level3 {
            get {
                return this.discountedRecurringPrice_Level3Field;
            }
            set {
                this.discountedRecurringPrice_Level3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedRecurringPrice_Level4 {
            get {
                return this.discountedRecurringPrice_Level4Field;
            }
            set {
                this.discountedRecurringPrice_Level4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedRecurringPrice_Level5 {
            get {
                return this.discountedRecurringPrice_Level5Field;
            }
            set {
                this.discountedRecurringPrice_Level5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedSetupCost_Level1 {
            get {
                return this.discountedSetupCost_Level1Field;
            }
            set {
                this.discountedSetupCost_Level1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedSetupCost_Level2 {
            get {
                return this.discountedSetupCost_Level2Field;
            }
            set {
                this.discountedSetupCost_Level2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedSetupCost_Level3 {
            get {
                return this.discountedSetupCost_Level3Field;
            }
            set {
                this.discountedSetupCost_Level3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedSetupCost_Level4 {
            get {
                return this.discountedSetupCost_Level4Field;
            }
            set {
                this.discountedSetupCost_Level4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DiscountedSetupCost_Level5 {
            get {
                return this.discountedSetupCost_Level5Field;
            }
            set {
                this.discountedSetupCost_Level5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object DownloadFile {
            get {
                return this.downloadFileField;
            }
            set {
                this.downloadFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EnableMultiChildAddToCart {
            get {
                return this.enableMultiChildAddToCartField;
            }
            set {
                this.enableMultiChildAddToCartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EnableOptions_InventoryControl {
            get {
                return this.enableOptions_InventoryControlField;
            }
            set {
                this.enableOptions_InventoryControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EstShip_2ndDay {
            get {
                return this.estShip_2ndDayField;
            }
            set {
                this.estShip_2ndDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EstShip_Ground {
            get {
                return this.estShip_GroundField;
            }
            set {
                this.estShip_GroundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object EstShip_Overnight {
            get {
                return this.estShip_OvernightField;
            }
            set {
                this.estShip_OvernightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost {
            get {
                return this.fixed_ShippingCostField;
            }
            set {
                this.fixed_ShippingCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Fixed_ShippingCost_Outside_LocalRegion {
            get {
                return this.fixed_ShippingCost_Outside_LocalRegionField;
            }
            set {
                this.fixed_ShippingCost_Outside_LocalRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object FreeShippingItem {
            get {
                return this.freeShippingItemField;
            }
            set {
                this.freeShippingItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object GiftWrapCost {
            get {
                return this.giftWrapCostField;
            }
            set {
                this.giftWrapCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Hide_FreeAccessories {
            get {
                return this.hide_FreeAccessoriesField;
            }
            set {
                this.hide_FreeAccessoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Hide_When_OutOfStock {
            get {
                return this.hide_When_OutOfStockField;
            }
            set {
                this.hide_When_OutOfStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Hide_YouSave {
            get {
                return this.hide_YouSaveField;
            }
            set {
                this.hide_YouSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object HowToGetSalePrice {
            get {
                return this.howToGetSalePriceField;
            }
            set {
                this.howToGetSalePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Inv_LastVerified {
            get {
                return this.inv_LastVerifiedField;
            }
            set {
                this.inv_LastVerifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Inv_Verify_QtyOnHand {
            get {
                return this.inv_Verify_QtyOnHandField;
            }
            set {
                this.inv_Verify_QtyOnHandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastPO_Date {
            get {
                return this.lastPO_DateField;
            }
            set {
                this.lastPO_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object LastPO_Qty {
            get {
                return this.lastPO_QtyField;
            }
            set {
                this.lastPO_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ListPrice_Name {
            get {
                return this.listPrice_NameField;
            }
            set {
                this.listPrice_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object MaxQty {
            get {
                return this.maxQtyField;
            }
            set {
                this.maxQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object METATAG_Description {
            get {
                return this.mETATAG_DescriptionField;
            }
            set {
                this.mETATAG_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object METATAG_Title {
            get {
                return this.mETATAG_TitleField;
            }
            set {
                this.mETATAG_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object MinQty {
            get {
                return this.minQtyField;
            }
            set {
                this.minQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Oversized {
            get {
                return this.oversizedField;
            }
            set {
                this.oversizedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Package_Type {
            get {
                return this.package_TypeField;
            }
            set {
                this.package_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Photo_AltText {
            get {
                return this.photo_AltTextField;
            }
            set {
                this.photo_AltTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Photo_SubText {
            get {
                return this.photo_SubTextField;
            }
            set {
                this.photo_SubTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PhotoURL_Large {
            get {
                return this.photoURL_LargeField;
            }
            set {
                this.photoURL_LargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object PhotoURL_Small {
            get {
                return this.photoURL_SmallField;
            }
            set {
                this.photoURL_SmallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Price_SubText {
            get {
                return this.price_SubTextField;
            }
            set {
                this.price_SubTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Price_SubText_Short {
            get {
                return this.price_SubText_ShortField;
            }
            set {
                this.price_SubText_ShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Private_Section_Customers_Only {
            get {
                return this.private_Section_Customers_OnlyField;
            }
            set {
                this.private_Section_Customers_OnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductCondition {
            get {
                return this.productConditionField;
            }
            set {
                this.productConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductKeywords {
            get {
                return this.productKeywordsField;
            }
            set {
                this.productKeywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductManufacturer {
            get {
                return this.productManufacturerField;
            }
            set {
                this.productManufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductNameShort {
            get {
                return this.productNameShortField;
            }
            set {
                this.productNameShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductPrice {
            get {
                return this.productPriceField;
            }
            set {
                this.productPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductPrice_Name {
            get {
                return this.productPrice_NameField;
            }
            set {
                this.productPrice_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductWeight {
            get {
                return this.productWeightField;
            }
            set {
                this.productWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Quickbooks_Item_Accnt {
            get {
                return this.quickbooks_Item_AccntField;
            }
            set {
                this.quickbooks_Item_AccntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Quickbooks_Item_AssetAccnt {
            get {
                return this.quickbooks_Item_AssetAccntField;
            }
            set {
                this.quickbooks_Item_AssetAccntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Quickbooks_Item_CogsAccnt {
            get {
                return this.quickbooks_Item_CogsAccntField;
            }
            set {
                this.quickbooks_Item_CogsAccntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Recurring_Pricing_Text {
            get {
                return this.recurring_Pricing_TextField;
            }
            set {
                this.recurring_Pricing_TextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RecurringDuration {
            get {
                return this.recurringDurationField;
            }
            set {
                this.recurringDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RecurringHowOften {
            get {
                return this.recurringHowOftenField;
            }
            set {
                this.recurringHowOftenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RecurringPrice {
            get {
                return this.recurringPriceField;
            }
            set {
                this.recurringPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RecurringStartDuration {
            get {
                return this.recurringStartDurationField;
            }
            set {
                this.recurringStartDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object RecurringStartPrice {
            get {
                return this.recurringStartPriceField;
            }
            set {
                this.recurringStartPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SalePrice_Name {
            get {
                return this.salePrice_NameField;
            }
            set {
                this.salePrice_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SelectedOptionIDs {
            get {
                return this.selectedOptionIDsField;
            }
            set {
                this.selectedOptionIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SetupCost {
            get {
                return this.setupCostField;
            }
            set {
                this.setupCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SetupCost_Name {
            get {
                return this.setupCost_NameField;
            }
            set {
                this.setupCost_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object SetupCost_Title {
            get {
                return this.setupCost_TitleField;
            }
            set {
                this.setupCost_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Ships_By_Itself {
            get {
                return this.ships_By_ItselfField;
            }
            set {
                this.ships_By_ItselfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ShoppingDotCom_Category {
            get {
                return this.shoppingDotCom_CategoryField;
            }
            set {
                this.shoppingDotCom_CategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object StockLowQtyAlarm {
            get {
                return this.stockLowQtyAlarmField;
            }
            set {
                this.stockLowQtyAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object StockReOrderQty {
            get {
                return this.stockReOrderQtyField;
            }
            set {
                this.stockReOrderQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TaxableProduct {
            get {
                return this.taxableProductField;
            }
            set {
                this.taxableProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object UPC_code {
            get {
                return this.uPC_codeField;
            }
            set {
                this.uPC_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Uses_Product_KeyTypes {
            get {
                return this.uses_Product_KeyTypesField;
            }
            set {
                this.uses_Product_KeyTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object VAT_Percentage {
            get {
                return this.vAT_PercentageField;
            }
            set {
                this.vAT_PercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Vendor_Price {
            get {
                return this.vendor_PriceField;
            }
            set {
                this.vendor_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object warehouses {
            get {
                return this.warehousesField;
            }
            set {
                this.warehousesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Yahoo_Category {
            get {
                return this.yahoo_CategoryField;
            }
            set {
                this.yahoo_CategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Yahoo_Medium {
            get {
                return this.yahoo_MediumField;
            }
            set {
                this.yahoo_MediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CUSTOM_METATAGS_OVERRIDE {
            get {
                return this.cUSTOM_METATAGS_OVERRIDEField;
            }
            set {
                this.cUSTOM_METATAGS_OVERRIDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ExtInfo {
            get {
                return this.extInfoField;
            }
            set {
                this.extInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object METATAG_Keywords {
            get {
                return this.mETATAG_KeywordsField;
            }
            set {
                this.mETATAG_KeywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object OrderFinished_Note {
            get {
                return this.orderFinished_NoteField;
            }
            set {
                this.orderFinished_NoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductDescription_AbovePricing {
            get {
                return this.productDescription_AbovePricingField;
            }
            set {
                this.productDescription_AbovePricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object ProductFeatures {
            get {
                return this.productFeaturesField;
            }
            set {
                this.productFeaturesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object TechSpecs {
            get {
                return this.techSpecsField;
            }
            set {
                this.techSpecsField = value;
            }
        }
    }
}
